- name: Setup aquarium rancher host
  hosts: aquarium
  remote_user: root
  roles:
    - docker
    - firewall
    - kerberos
    - perun
    - ssh
    - igtf_certificates
    - auto_update
    - monitoring
    - utilities
