- name: Setup seahorse rancher worker nodes (i.e. horse)
  hosts: seahorse
  remote_user: root
  roles:
    - docker
    - firewall
    - kerberos
    - perun
    - ssh
    - igtf_certificates
    - auto_update
    - monitoring
    - utilities
