---

- name: ensure metacentrum repo is present
  include_role:
    name: metacentrum_repo

- name: install perun packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - perun-slave-meta-key
    - perun-slave-process-k5login-root
